services:
  postgres:
    image: docker.io/postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  firefox:
    image: ghcr.io/ambry-app/firefox-headless-marionette:latest
    ports:
      - 2828:2828
    restart: unless-stopped

volumes:
  pgdata:
