defmodule Ambry.Ecto.UtcDateTimeMs do
  @moduledoc """
  A UTC datetime type with millisecond precision.

  Unlike `:utc_datetime_usec` which requires 6 decimal places, this type
  requires exactly 3 decimal places (millisecond precision).

  Returns an error if the DateTime has the wrong precision - it's the
  caller's responsibility to supply a DateTime with the correct precision.

  ## Example

      # Creating a DateTime with millisecond precision
      DateTime.utc_now() |> DateTime.truncate(:millisecond)
      #=> ~U[2026-01-08 20:44:42.519Z]

      # This will fail - microsecond precision (6 digits)
      DateTime.utc_now()
      #=> ~U[2026-01-08 20:44:42.519123Z]

      # This will fail - second precision (0 digits)
      DateTime.utc_now() |> DateTime.truncate(:second)
      #=> ~U[2026-01-08 20:44:42Z]

  ## Autogenerate

  This type supports autogeneration for Ecto timestamps:

      timestamps(type: Ambry.Ecto.UtcDateTimeMs)

  The autogenerated values will have millisecond precision.
  """
  use Ecto.Type

  @impl true
  def type, do: :utc_datetime_usec

  @doc """
  Generates a UTC DateTime with millisecond precision.

  Used by Ecto's `timestamps/1` macro for auto-generating `inserted_at`
  and `updated_at` fields.
  """
  @impl true
  def autogenerate, do: DateTime.utc_now() |> DateTime.truncate(:millisecond)

  def from_unix!(microseconds, :microsecond) do
    microseconds |> DateTime.from_unix!(:microsecond) |> DateTime.truncate(:millisecond)
  end

  @impl true
  def cast(%DateTime{microsecond: {_, 3}} = dt), do: {:ok, dt}

  def cast(%DateTime{microsecond: {_, precision}}),
    do: {:error, message: "expected millisecond precision (3), got: #{precision}"}

  def cast(_), do: :error

  @impl true
  def load(%DateTime{} = dt), do: {:ok, dt |> DateTime.truncate(:millisecond)}

  def load(%NaiveDateTime{} = ndt),
    do: {:ok, DateTime.from_naive!(ndt, "Etc/UTC") |> DateTime.truncate(:millisecond)}

  def load(_), do: :error

  @impl true
  def dump(%DateTime{microsecond: {_, 3}} = dt), do: {:ok, dt}

  def dump(%DateTime{microsecond: {_, precision}}),
    do: {:error, message: "expected millisecond precision (3), got: #{precision}"}

  def dump(_), do: :error
end
